# Generated by Django 5.2.4 on 2025-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_quote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
