# Generated by Django 5.2.4 on 2025-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quote_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
