# Generated by Django 5.2.4 on 2025-09-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_subscription"),
        ("core", "0005_alter_quote_text"),
    ]

    operations = []
